AllCops:
  TargetRubyVersion: 2.0

# Although it is a good idea to documentation at a class level, developers should
# not be forced to add a documentation. Because good naming or usefull conventions
# might make documentation redundant.
Documentation:
  Enabled: false

# Because 80 would be too short and 99 fits perfectly into the code sections on
# GitHubs PR pages
Metrics/LineLength:
  Max: 99

# We are way above the recommended maximum of 100 and this counter changes quite
# offen. Let's pin this to a unreasonable high number to avoid noise
Metrics/ClassLength:
  Max: 512
